all:
  children:
    builder:
      hosts:
        azure-builder:
          ansible_host: 203.0.113.10
          ansible_connection: winrm
          ansible_port: 5986
          ansible_user: runneradmin
          ansible_password: CHANGE_ME
          ansible_shell_type: powershell
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 90
