using System;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Relics;
using SpireLens.Core;
using SpireLens.Core.Patches;
using Xunit;

namespace SpireLens.Core.Tests;

public class BurningSticksStatsTests
{
    private const string BurningSticksRelicId = "RELIC.BURNING_STICKS";

    private static readonly MethodInfo BuildBodyMethod =
        typeof(RelicHoverShowPatch).GetMethod(
            "BuildBurningSticksBodyBBCode",
            BindingFlags.NonPublic | BindingFlags.Static)
        ?? throw new InvalidOperationException("BuildBurningSticksBodyBBCode not found.");

    [Fact]
    public void Patch_TargetsBurningSticksAfterCardExhaustedWithExpectedParameters()
    {
        var target = typeof(BurningSticks).GetMethod(nameof(BurningSticks.AfterCardExhausted));

        Assert.NotNull(target);
        Assert.Equal(
            new[] { typeof(PlayerChoiceContext), typeof(CardModel), typeof(bool) },
            target!.GetParameters().Select(parameter => parameter.ParameterType));
    }

    [Fact]
    public void RelicAggregate_BurningSticksFields_DefaultToZero()
    {
        var agg = new RelicAggregate();

        Assert.Equal(0, agg.Activations);
        Assert.Equal(0, agg.BurningSticksCombats);
        Assert.Equal(0, agg.BurningSticksGeneratedCardPlays);
        Assert.Equal(0, agg.BurningSticksCommonCardsDuplicated);
        Assert.Equal(0, agg.BurningSticksUncommonCardsDuplicated);
        Assert.Equal(0, agg.BurningSticksRareCardsDuplicated);
    }

    [Fact]
    public void RelicAggregate_BurningSticksFields_JsonRoundtripPreservesValues()
    {
        var run = new RunData();
        run.RelicAggregates[BurningSticksRelicId] = PopulatedAggregate();

        var json = JsonSerializer.Serialize(run, RunStorage.Options);
        var restored = JsonSerializer.Deserialize<RunData>(json, RunStorage.Options);

        Assert.Contains("\"burning_sticks_combats\"", json);
        Assert.Contains("\"burning_sticks_generated_card_plays\"", json);
        Assert.Contains("\"burning_sticks_common_cards_duplicated\"", json);
        Assert.Contains("\"burning_sticks_uncommon_cards_duplicated\"", json);
        Assert.Contains("\"burning_sticks_rare_cards_duplicated\"", json);
        Assert.NotNull(restored);
        AssertAggregate(restored!.RelicAggregates[BurningSticksRelicId]);
    }

    [Fact]
    public void RunTracker_BurningSticksHelpers_CountOnlySuccessfulDuplicatesAndActualPlays()
    {
        var agg = new RelicAggregate();

        RunTracker.RecordBurningSticksDuplicateForTest(agg, true, CardRarity.Common);
        RunTracker.RecordBurningSticksDuplicateForTest(agg, true, CardRarity.Uncommon);
        RunTracker.RecordBurningSticksDuplicateForTest(agg, true, CardRarity.Rare);
        RunTracker.RecordBurningSticksDuplicateForTest(agg, false, CardRarity.Rare);
        RunTracker.RecordBurningSticksGeneratedCardPlayedForTest(agg, 5);
        RunTracker.RecordBurningSticksGeneratedCardPlayedForTest(agg, -1);
        RunTracker.RecordBurningSticksCombatForTest(agg, 4);
        RunTracker.RecordBurningSticksCombatForTest(agg, 0);

        AssertAggregate(agg);
    }

    [Fact]
    public void RelicAggregate_BurningSticksFields_Merge()
    {
        var target = PopulatedAggregate();

        RunTracker.MergeRelicAggregateInto(target, PopulatedAggregate());

        Assert.Equal(6, target.Activations);
        Assert.Equal(8, target.BurningSticksCombats);
        Assert.Equal(10, target.BurningSticksGeneratedCardPlays);
        Assert.Equal(2, target.BurningSticksCommonCardsDuplicated);
        Assert.Equal(2, target.BurningSticksUncommonCardsDuplicated);
        Assert.Equal(2, target.BurningSticksRareCardsDuplicated);
    }

    [Fact]
    public void RelicTooltip_BurningSticks_ShowsRequestedTotalsAndAverages()
    {
        var body = BuildBody(PopulatedAggregate());

        Assert.Contains("successfully duplicated an exhausted Skill", body);
        Assert.Contains("Successful Burning Sticks activations divided by combats", body);
        Assert.Contains("Finished plays of cards generated by Burning Sticks", body);
        Assert.Contains("Common cards successfully duplicated", body);
        Assert.Contains("Uncommon cards successfully duplicated", body);
        Assert.Contains("Rare cards successfully duplicated", body);
        Assert.Contains("[b]0.75[/b]", body);
        Assert.Contains("[b]1.25[/b]", body);
    }

    [Fact]
    public void RelicAggregate_OlderShapeWithoutBurningSticksFields_DefaultsToZero()
    {
        var agg = JsonSerializer.Deserialize<RelicAggregate>("{}", RunStorage.Options);

        Assert.NotNull(agg);
        Assert.Equal(0, agg!.BurningSticksCombats);
        Assert.Equal(0, agg.BurningSticksGeneratedCardPlays);
        Assert.Equal(0, agg.BurningSticksCommonCardsDuplicated);
        Assert.Equal(0, agg.BurningSticksUncommonCardsDuplicated);
        Assert.Equal(0, agg.BurningSticksRareCardsDuplicated);
    }

    private static RelicAggregate PopulatedAggregate()
        => new()
        {
            Activations = 3,
            BurningSticksCombats = 4,
            BurningSticksGeneratedCardPlays = 5,
            BurningSticksCommonCardsDuplicated = 1,
            BurningSticksUncommonCardsDuplicated = 1,
            BurningSticksRareCardsDuplicated = 1,
        };

    private static void AssertAggregate(RelicAggregate agg)
    {
        Assert.Equal(3, agg.Activations);
        Assert.Equal(4, agg.BurningSticksCombats);
        Assert.Equal(5, agg.BurningSticksGeneratedCardPlays);
        Assert.Equal(1, agg.BurningSticksCommonCardsDuplicated);
        Assert.Equal(1, agg.BurningSticksUncommonCardsDuplicated);
        Assert.Equal(1, agg.BurningSticksRareCardsDuplicated);
    }

    private static string BuildBody(RelicAggregate agg)
        => (string)(BuildBodyMethod.Invoke(null, new object[] { agg })
                    ?? throw new InvalidOperationException("Builder returned null."));
}
